#+OPTIONS: toc:nil

#+LATEX_CLASS:    koma-article  
#+LATEX_HEADER:   \usepackage[a4paper]{geometry}
#+LATEX_HEADER:   \usepackage{libertine, microtype, graphicx, float, booktabs, amsmath, siunitx}
#+LATEX_HEADER:   \usepackage[USenglish]{babel}
#+LATEX_HEADER:   \usepackage[scaled=0.9]{inconsolata}
#+LATEX_HEADER:   \usepackage[libertine]{newtxmath}

#+LATEX_HEADER:   \setkomafont{captionlabel}{\sffamily\bfseries}
#+LATEX_HEADER:   \setcapindent{0em}  \setkomafont{caption}{\small}
#+LATEX_HEADER:   \usepackage[basicstyle=small]{listings}

# name: Readme JOSS_bibliographies
# date: 2019-07-08 (YYYY-MM-DD)

#+TITLE:  =JOSS_biliographies=

* Background

  Publications of the Journal of Open Source Software (JOSS[fn:1]) are
  equally available as =.html= and =.pdf=, altogether with their
  corresponding =.xml= files, on a separate public repository[fn:2].
  This not only offers an alternative access to the publications /at
  once/, equally, it is possible to retrieve their bibliographic data
  rapidly for further processing in literature reference programs like
  zotero[fn:3]

* Technique deployed

  The uncompressed =.zip= archive is cloned onto a machine running
  =Python3=.  The branch was chosen both because of the anticipated
  retirement of =Python2=, as well for the better support of Unicode
  characters.  Both scripts run from the CLI, and expect the =.zip=
  archive in the same folder, e.g.
  #+BEGIN_SRC python
    python bibtool_Joss_pocket.pt joss-papers-master.zip
  #+END_SRC
  and currently will briefly extract the complete content of the
  archive.  At present (2019-Jun-08), this requires about 0.3 to
  0.4 GB freely accessible space on the hard disk.

  The smaller script, =joss-papers-master.zip= retrieves the small
  «cite as» block provided on each =.html= of the corresponding
  publication, in either =.txt= or =.csv= format.  The larger
  =bibtool_Joss_bibtex.py= attempts to retrieve /basic/ bibliographic
  information and creation of a bibtex file (=.bib=) understood by
  many literature reference programs.  In addition, a less verbose
  =.csv= (separator: semicolon) is created, offering futher processing
  with any editor, or spreadsheet.

  After running these scripts, the scripts leave you with the original
  =.zip= archive (still containing the =.html= and =.pdf= about the
  publications) and the extracted literature data.  Intermediate files
  are deleted automatically.

* Copyright
  (c) 2019 Norwid Behrnd, GPLv3.



* Footnotes

[fn:3] [[http://www.zotero.org][http://www.zotero.org]]

[fn:2] https://github.com/openjournals/joss-papers 

[fn:1] https://joss.theoj.org/

